"use strict";
console.log("_".repeat(20));
console.log(7 + 1);
console.log("_".repeat(20));
console.log(9 - 1);
console.log("_".repeat(20));
console.log(2 * 4);
console.log("_".repeat(20));
console.log(64 / 8);
console.log("_".repeat(20));
